Update Jenkinsfile.DeployHoL

diff --git a/ClouderaSetup/OnCloud/AWS/build/Jenkinsfile.DeployHoL b/ClouderaSetup/OnCloud/AWS/build/Jenkinsfile.DeployHoL
--- a/ClouderaSetup/OnCloud/AWS/build/Jenkinsfile.DeployHoL
+++ b/ClouderaSetup/OnCloud/AWS/build/Jenkinsfile.DeployHoL
@@ -399,12 +399,16 @@ HOSTEDZONEID:${params.HOSTEDZONEID}
                     fi
                     
                     echo "➡️  Assigning role '$role_name' to user '${CDP_USER_CRN}'..."
-                    
+
+                    # Temporarily disable the "exit on error" behavior
+		    set +e
                     output=$(cdp iam assign-user-resource-role \
                         --user "$CDP_USER_CRN" \
                         --resource-role-crn "$role_crn" \
                         --resource-crn "$CDP_ENV_CRN" 2>&1)
                     exit_status=$?
+		    # Re-enable "exit on error" for the rest of the script
+		    set -e
 		    echo "check_output"
 
                     if [ $exit_status -eq 0 ]; then
